spring:
  application:
    name: rpc-provider
  banner:
    location: banner.txt
# logger
logging:
  level:
    com.nz.rpc: debug


server:
  port: 8464
nzrpc:
  zookeeper:
    address: "127.0.0.1:2181"
  netty:
    port: 8121
    host: "127.0.0.1"
  uid:
    type: custom
    macId: 1