server:
  port: 8112
spring:
  application:
    name: rpc-provider
nzrpc:
  zookeeper:
    address: "127.0.0.1:2181"
  netty:
    port: 8122
  serialization: hessian
  uid:
    type: custom
    macId: 123
  nettyClient:
    workerTheads: 4

# logger
logging:
  level:
    com: debug
    org: debug
    org.apache.zookeeper: error
    org.apache.tomcat: error
    org.apache.coyote: error
#    com.nz.rpc: debug
 #   com.nz.rpc.msg.ClientMessageHandler: error
  #  com.nz.rpc.netty.coder.MsgCoder: error
