spring:
  application:
    name: rpc-client

#zookeeper
zookeeper:
  host: 127.0.0.1
  port: 2181

# logger
logging:
  level:
    com.nz.rpc: debug
    org.apache.zookeeper: error
server:
  port: 8223
