server:
  port: 8482
spring:
  application:
    name: dubbo-provider2


logging:
  level:
    com.dubbo: debug
dubbo:
  application:
    name: dubbo-provider2
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882