spring:
  application:
    name: rpc-provider
  banner:
    location: banner.txt
# logger
logging:
  level:
    com: debug
    com.nz.rpc.netty.coder.MsgCoder: info
    com.nz.rpc.netty.server.handler.HeartbeatResponseHandler: info
   # com.nz.rpc: debug
    #com.nz.rpc.netty.server.handler.HeartbeatResponseHandler: info
    #com.nz.rpc.netty.coder.MsgCoder: info
server:
  port: 8464
nzrpc:
  zookeeper:
    address: "127.0.0.1:2181"
  netty:
    port: 8121
    host: "127.0.0.1"
  uid:
    type: custom
    macId: 1
  nettyServer:
    bossTheads: 2
    workerTheads: 8
  serialization: hessian