server:
  port: 8110
spring:
  application:
    name: rpc-provider
nzrpc:
  zookeeper:
    address: "127.0.0.1:2181"
  netty:
    port: 8121
  data: "assssss"
# logger
logging:
  level:
    com.nz.rpc: debug